README.md
I had to change the init and update function to use a tuple of #(state, cmd) and to make the Action type public. Gleam format added some noise to the diff
=> docs: fix the example so that it compiles

src/lustre/attribute.gleam
`for` can't be use in JS as it's a reserved keyword, so react renamed the property to `htmlFor`
=> output `htmlFor` instead of `for`

manifest.toml, src/ffi.mjs, test/example/application/counter.gleam, test/example/main.gleam, test/playground/monaco.gleam
3-in-1
Fix: avoid a race condition when dispatch is used twice from outside
E.g. websocket open + websocket msg arriving
Application returns a Cmd from update(model, msg)
but the Effect handler is *not* ran be React 18 before
the websocket msg-arriving is handled by the Reducer.
Result: The Cmd returned by update(model, msg) is dropped silently.
=> Fix: avoid a race condition when dispatch is used twice from outside

src/lustre/attribute.gleam, src/lustre/element.gleam
Fixes #12, class and style attributes are no longer duplicated in statically generated html.
Renames `to_string` to `to_string_parts` in src/lustre/attribute.gleam, and changes return type from `String` to `Option(#(String, String))`.
Also updates `attrs_to_string_builder` to handle this change.
=> Combine class and style attributes

README.md
I tried running the example in the README, and realized that `app` was missing from `lustre.start`.
=> docs: Fix small typo in README example so that it works.

src/http.ffi.mjs
Some browsers would try loading favicon which causes a 404 Not Found error, craching the Http server:
```shell
$ gleam run -m lustre/try --target javascript
Compiled in 0.04s
Running lustre/try.main
node:internal/errors:496
ErrorCaptureStackTrace(err);
^
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Error
at new NodeError (node:internal/errors:405:5)
at write_ (node:_http_outgoing:875:11)
at ServerResponse.end (node:_http_outgoing:1026:5)
at file:///D:/github/lustre_ui/demo/build/dev/javascript/lustre/http.ffi.mjs:82:15 {
code: 'ERR_INVALID_ARG_TYPE'
}
```
This PR fixes it.
=> 🐛 Fixed a bug where lustre/try crashes on 404 (javascript target)

gleam.toml, manifest.toml, src/http.ffi.mjs, src/http_ffi.erl, src/lustre/try.gleam
=> Add logging to `lustre/try`

gleam.toml, manifest.toml, src/http.ffi.mjs, src/http_ffi.erl, src/lustre/try.gleam
Uses [glint](https://hexdocs.pm/glint/glint.html#run) to parse CLI args for `--host` and `--post` as well as the flag `--include-styles` to add the lustre_ui stylesheet via jsdelivr.
```
% gleam run -m lustre/try -- --help                                                
Compiling lustre
Compiled in 0.18s
Running lustre/try.main
USAGE:
gleam run -m lustre/try [ ARGS ] [ --host=<STRING> --include-styles=<BOOL> --port=<INT> ]
FLAGS:
--help                  Print help information
--host=<STRING>         The host to run the server on
--include-styles=<BOOL>         Include lustre_ui's default stylesheet in your app.
--port=<INT>            The port to run the server on
```
There are outstanding issues on the glint repo to fix some things or improve the output of this help text:
- …
=> ✨ Add flags for configuring the server's host and port.

src/lustre/attribute.gleam
This PR fixes (what appears to be) a bug in the `autofocus` attribute.
I'm still not quite clear on the differences between properties and attributes, so it's possible I've misunderstood something 😅
Here is what I ran into:
When using `autofocus(True)` I don't see the `autofocus` attribute being applied to the `div` in the DOM:
```gleam
div([autofocus(True)], [])
```
However, if I apply it manually and use `"autofocus"` instead of `"autoFocus"` then it works as expected:
```gleam
div([property("autofocus", True)], [])
```
=> Fix `autofocus` property name

docs/guide/01-quickstart.md
A couple of tiny spelling mistakes 🙂
=> Fix typos in quickstart guide

README.md
=> Fix link to Quickstart guide

src/lustre/cli/esbuild.gleam
I'm trying to run `gleam run -m lustre build app` inside of a linux docker container on an M1 Macbook.  However, it prints the following statement and exits:
```
I couldn't figure out the correct esbuild version for your
os (linux) and cpu (aarch64)
```
Looking at the [official esbuild download script](https://github.com/evanw/esbuild/blob/main/dl.sh) it looks like they download the `arm64` version for `aarch64` architectures.
I've added a download case based on the same idea.
=> Add support for linux aarch64 esbuild

src/lustre/internals/vdom.gleam
As per our Discord discussion. This makes dangerous inner HTML appear when `element.to_string` is used.
This was tested with a path dep on RC2.
=> Fix stringifying dangerous HTML attribute

pages/guide/02-state-management.md
There are also a lot of references to "the model", and in a bunch of them I wonder whether it should be capitalized as `Model`. For example:
> It is overwhelmingly common to see the model of a Lustre application
> Here, we have a model that represents our application
I will leave that up to your editorial choices 😄
=> Fix typos in State Management guide

birdie_snapshots/can_safely_escape_dangerous_symbols_in_attributes.accepted, src/lustre/internals/vdom.gleam, test/apps/static.gleam, test/lustre_test.gleam
this is to fix situations where attributes have quotes in their value such as:
```
div([attribute("example", "{\"mykey\": \"myvalue\"}")], [])
```
where the result when rendered in the browser is:
```
<div example="{" mykey":="" "myvalue"}"=""></div>
```
which now becomes:
```
<div example="{&quot;mykey&quot;: &quot;myvalue&quot;}"></div>
```
or as seen from the developer console:
---
let me know if you want me to split the new test into a different app file or anything like that.
also, I only changed it for custom key/value pair, not when pattern matching on "class" and "style", i expect we'll want it here as well and extent the test coverage as well? just wanted to do a first pass implementation to verify i'm changing all the right bits before changing too much ha. let me know.
=> add escape function over custom attribute values

pages/reference/for-elm-devs.md, pages/reference/for-react-devs.md
I used code samples (when available) from the React cheatsheet branch, and filled out all of the same headings - with the only exception being the "Components" heading, since "Elm applications don't have components" 😂
=> Lustre for Elm Developers cheatsheet

src/client-runtime.ffi.mjs
If not in a browser then `window` may not be defined, resulting in a crash
I ran a command wrong and this happened:
```
$ gleam run -- -m lustre/dev --help
Compiled in 0.04s
Running app.main
file:///Users/louis/src/gleam/html_lustre_converter/app/build/dev/javascript/lustre/client-runtime.ffi.mjs:170
export const is_browser = () => window && window.document;
^
ReferenceError: window is not defined
at is_browser (file:///Users/louis/src/gleam/html_lustre_converter/app/build/dev/javascript/lustre/client-runtime.ffi.mjs:170:40)
at Module.start (file:///Users/louis/src/gleam/html_lustre_converter/app/build/dev/javascript/lustre/lustre.mjs:101:6)
at main (file:///Users/louis/src/gleam/html_lustre_converter/app/build/dev/javascript/app/app.mjs:7:19)
at …
```
=> Fix crash in is_browser when misused

src/lustre-escape.ffi.mjs, src/lustre/internals/escape.gleam, src/lustre/internals/vdom.gleam, src/lustre_escape_ffi.erl
This PR replaces the `escape` function with an implementation optimised specifically for each target:
- There's a highly optimised version for escaping on the Erlang target, it's performance is now on par with what `Phoenix.HTML` does when producing an escaped String.
- For the JavaScript one the implementation is generic enough that it could also work on the Erlang target but it's a bit less efficient so I decided to still split the two implementations
- I moved the implementations to another internal module because I ended up using `@target` quite a bit and didn't really like having it inside the VDOM module (but that's just vibes, if you want I can put everything back there)
Also it would be nice if we had a "real" page to render and see the actual difference in performance between the …
=> ⚡️ Optimise escape function

src/lustre/internals/vdom.gleam
The JSON representation of a fragment didn't  match the JS representation, and was missed when the vdom was rendering the elements. Updated the representation to match what is expected by the vdom impl (and also what is used in a full client side application)
=> 🐛 Update JSON structure of a Fragment to match JS structure

src/lustre/element.gleam
I noticed the old escape function still in the code. It's unused so I removed it (the compiler didn't mark it as unused since it's recursive, but that's a know bug <https://github.com/gleam-lang/gleam/issues/2634>)
=> :coffin: Remove unused `escape` function

pages/guide/04-server-side-rendering.md
The paragraph will make sense once #92 is done.
=> Remove a paragraph referencing a non-existent guide

src/vdom.ffi.mjs
In lustre 4.3.0, a bug happens when combining fragments and `element.map`. Below, a simple, small reproducible example.
<details><summary>Reproducible Example</summary>
<p>
```gleam
import gleam/int
import lustre
import lustre/element.{text}
import lustre/element/html.{button, div, p}
import lustre/event.{on_click}
pub fn main() {
let app = lustre.simple(init, update, view)
let assert Ok(_) = lustre.start(app, "#app", Nil)
Nil
}
fn init(_flags) {
0
}
type Msg {
Counter(Counter)
}
type Counter {
Incr
Decr
}
fn update(model, msg) {
case msg {
Counter(Incr) -> model + 1
Counter(Decr) -> model - 1
}
}
fn view(model) {
let count = int.to_string(model)
element.map(
div([], [
button([on_click(Incr)], [text(" + ")]),
p([], [text(count)]),
bloup(),
p([], [text(count)]),
bloup(),
p([], …
```
=> :bug: Fix when a Fragment is put in VDOM stack, because of Map

pages/guide/08-components.md
First ever pull request! Let's see how this goes :-)
I was reading the Lustre docs and came across this usage of `variant: Variant` while the defined type seem to be called `MyButtonVariant`
=> fix: fix type typo

src/lustre/effect.gleam
I found it hard to figure out exactly how it should be used without clicking through to the code where the variable names helped me a little.
I hope that this could be useful to include. I'm not sure how we feel about having other libraries in code examples. I guess I like the idea of its being more real world but I also realise that plinth library might change and render this out of date which isn't so great. 
I'm not sure if any core libraries expose a repeater timer concept as that could also be a real world example. To refresh some data every minute or something.
=> Add example for effect.from

src/vdom.ffi.mjs
Small fix here, but this was breaking for a specific use case:
```
el.fragment([
el.map(...),
])
```
Because the map pushed in the tree. Going through `iterateElement` remove any undesired `Element` in the tree (i.e. `Fragment` & `Map`).
=> Fix fragment that could be pushed in tree, which is invalid

src/lustre/attribute.gleam
Replaced ` ` (space) with `,` (comma), as the valid attribute value is set of comma-separated token.
spec: <https://html.spec.whatwg.org/multipage/input.html#attr-input-accept>
=> Fix `accept` using incorrect separator

pages/guide/04-spa-deployments.md
update: I added GitHub Pages in this patch as well 🙂
here is the companion demo repo that I used to make sure it works:
https://github.com/ollema/lustre-spa-deployment
and the associated workflows:
https://github.com/ollema/lustre-spa-deployment/blob/main/.github/workflows/github_pages.yml
https://github.com/ollema/lustre-spa-deployment/blob/main/.github/workflows/cloudflare_pages.yml
and the resulting deployments:
https://ollema.github.io/lustre-spa-deployment/
https://lustre-spa-deployment.pages.dev/
let me know if I missed anything!
some thoughts:
- I'm including a build step here in the workflow but it is not strictly needed if you have not .gitignored the priv/ directory but then it's up to the user to remember to build before you push. could simplify the workflow a lot if we only …
=> :memo: add deployment guide for SPAs

src/lustre-escape.ffi.mjs, src/lustre/internals/patch.gleam, src/lustre/internals/runtime.gleam, src/lustre/internals/vdom.gleam
This PR replaces all calls to the deprecated `dynamic.unsafe_coerce` with an external function.
=> :recycle: Replace deprecated unsafe_coerce calls

src/lustre.gleam
I'm new to lustre and this was the first link to the quickstart guide I tried. Took a few minutes to try to find the right one. Hopefully this small fix helps other beginners!
Appears on this page: https://hexdocs.pm/lustre/lustre.html
=> docs: fix quickstart link

src/vdom.ffi.mjs
Fixed the problem where children of element.keyed elements would be added instead of the elements themselves.
It seems like the problem was a for-loop looping though the children of each child and adding them instead of the child itself when there were no keyed children.   
I left the `prevChild` behaviour because I am not sure of how it works.   
Also, I guess the for-loop was here for a reason, so I hope the change doesn't break anything. It does appear to fix the problem though
=> :bug: Fixed element.keyed children

gleam.toml
Lustre uses the internal annotation so it requires a gleam version that is at least >= 1.1.0 to compile
=> :rotating_light: Update gleam version constraint

pages/guide/01-quickstart.md, pages/hints/rendering-lists.md, src/lustre/element.gleam
This PR adds docs for considerations around rendering lists, discussing the duplicate image issue that can be seen in the quickstart tutorial, and how to solve this using `element.keyed`.
The quickstart tutorial page has a brief note explaining this, with a link to the new docs. Currently the docs are in the `hints` folder. I think all the `hints` docs probably warrant becoming links in the main `pages` menu of the docs, even if they remain in the `hints` folder (or add a `hints` menu section if that's possible). This increases their visibility (I only found the two exisiting hints from browsing the repo). This piece of work is not yet done, since I'm unsure if you'd prefer to structure the menu or file locations.
You are most welcome to change/edit any of the docs I've created to fit any …
=> Add docs about rendering lists

pages/reference/for-react-devs.md
I've been sitting on this for literally weeks. Got hung up on "perfect".
I also promised a friend I would make the PR this week.
---
I took inspiration from the [elm cheatsheet](https://hexdocs.pm/lustre/cheatsheets/elm.html) & [03 Side effects](https://hexdocs.pm/lustre/guide/03-side-effects.html) in writing these sections, but realized the best example was actually the [quickstart](https://hexdocs.pm/lustre/guide/01-quickstart.html). I think the cheatsheets should all converge into the same "app" as the quickstart.
=> 📝Added missing sections to React cheatsheet

pages/guide/01-quickstart.md
The application compiles for the user when building examples from the [01-quickstart](https://hexdocs.pm/lustre/guide/01-quickstart.html) page, but sadly, no cats appear due to the previous random cat API's availability (often, slow or no response).
The new API seems to work better, though since it returns a list with one cat by default, slightly more complex code was necessary to accommodate the differing response shape.  (A good learning experience for me.)
=> Fix: Rely on thecatapi.com for 01-Quickstart page examples

src/lustre/attribute.gleam
The property is actually named "readOnly" rather than "readonly". This fixes #201.
Verified with the following code snippet:
```gleam
pub fn main() {
let app = lustre.element(html.input([attribute.property("readOnly", True)]))
let assert Ok(_) = lustre.start(app, "#app", Nil)
Nil
}
```
=> Fix property readonly.

gleam.toml
https://discord.com/channels/768594524158427167/768594524158427170/1299056516170514442
i wanted to use gleam json in my lustre project
this PR is just to show the issue not the fix also this package 
- gleam_community_colour
has the same issue the lustre package have and lustre depends on it
=> Change toml file to accept installing gleam_json@2 in your lustre project

src/vdom.ffi.mjs
This test fails on node and I am using lustre to build pages on a node server.
This fixes the crash I see.
Note I've only fixed use of window here as this is the only one outside a function definition and therefore doesn't get shaken away in a bundle step
=> use globalThis at top level

pages/guide/01-quickstart.md
When following the quickstart script, I found that the increment button behaved correctly, but clicking the decrement button reduced the count without removing an image.
=> Decrement msg should remove an image

pages/guide/06-full-stack-applications.md
I think this command was intended to be:
```sh
mkdir lustre-fullstack-guide \
&& cd lustre-fullstack-guide \
&& gleam new client --name app \
&& gleam new server --name app \
&& gleam new shared --name app
```
=> Fixed minor doc error for full-stack guide

src/lustre.ffi.mjs
There was a typo, where the code read "mirrored" and wrote "mirrorred" (two Rs). Thus the `prev` value was always `undefined` and the decoder was called every time.
=> Fix always calling decoder even if value didn't change

src/lustre/attribute.gleam
Small PR to add an `attribute.data/2` helper function to add data attributes to HTML elements. I added some small doc but I feel like it would benefit from some improvement.
=> Add attribute.data helper function

src/lustre/attribute.gleam
This PR add 2 new attributes that allows one to set the [`crossorigin`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin) and [`integrity`](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) attributes for `link` and `script` elements.
=> Allows setting link crossorigin integrity attributes

src/lustre/attribute.gleam
This allows us to do
```gleam
html[[lang("en")], [...]]
```
=> Adds the `lang` attribute

benchmarks/table-editor/src/app.gleam, benchmarks/table-editor/src/column.gleam, src/adopt_stylesheets.mjs, src/runtime.ffi.mjs
- **Unify SPA/Component runtime** \
This worked out better than I thought, I hope it can stay this way once we add hydration/magic slots
- **Change event dispatch order** \
In the old version, messages dispatched from effects where handled immediately. The new runtime has a queue that handles them in-order. That means after an update all effects are processed _first_, and only _then_ the next message is handled.
- **Defer renders to the next animation frame** \
While updates are processed synchronously, view is deferred when possible to the next animation frame, unless the `immediate` flag is set on the event.
=> Client runtime improvements

pages/guide/01-quickstart.md
When playing with the quickstart docs, I noticed that there is a new decoder package. Updated the docs :1234:
=> 🧩 Use new decoder in quickstart docs

UPGRADE_GUIDE.md, benchmarks/table-editor/src/column.gleam, src/lustre/attribute.gleam, src/lustre/internals/constants.gleam, src/lustre/runtime/client/core.ffi.mjs, src/lustre/runtime/client/reconciler.ffi.mjs, src/lustre/runtime/client/server_component_reconciler.ffi.mjs, src/lustre/runtime/client/virtualise.ffi.mjs, src/lustre/vdom/attribute.gleam, src/lustre/vdom/diff.gleam, test-apps/keyed-diffs/src/app.ffi.mjs, test/tests/diff_test.gleam
I changed the diff to diff keyed elements like normal, if an old/new pair would have been a replace previously. This means nodes can be gracefully "upgraded" from non-keyed to keyed nodes, making virtualisation more useful. The only reason we bail now is when using fragments.
All boolean properties are attributes now, which means we can support them during SSR as well. I tested them all and added hooks that sync them to a property when the browser does not automatically do that already.
`autofocus` and `autoplay` are special-cased to trigger their associated action when changing their value from `False` to `True`.
=> Virtualisation!

pages/guide/06-full-stack-applications.md
`nil_error` no longer exists in gleam/result, so I've replaced it with `replace_error(Nil)`
=> Replace `nil_error` with  `replace_error(Nil)` in docs

examples/03-effects/04-local-storage/README.md, examples/03-effects/04-local-storage/gleam.toml, examples/03-effects/04-local-storage/index.html, examples/03-effects/04-local-storage/src/app.ffi.mjs, examples/03-effects/04-local-storage/src/app.gleam, examples/03-effects/04-local-storage/tailwind.config.js, src/lustre.gleam, src/lustre/attribute.gleam, src/lustre/component.gleam, src/lustre/effect.gleam, src/lustre/element.gleam, src/lustre/element/keyed.gleam, src/lustre/event.gleam, src/lustre/server_component.gleam, src/lustre/vdom/patch.gleam
Closes #284 and partially #283. It turns out finding a reference for All The Attributes is quite difficult. This PR expands the number of attributes Lustre provides to ~150 including ARIA attributes. Many but not all of these attributes have hand-written documentation inspired by the spec. The remaining attributes have a brief doc comment sourced from the spec directly.
When I started this work I removed all the attributes currently in the module so I could better organise things, it's possible we lost some along the way.
=> Add many more attributes to `lustre/attribute`.

src/lustre/element/keyed.gleam
Very tiny PR just fixing a misspelling I found in the docs, updating `conuter` to `counter`.
=> Fix miss-spelling in keyed.gleam docs

README.md
=> :memo: make  link absolute, point to hexdocs

CHANGELOG.md, src/lustre/attribute.gleam, src/lustre/vdom/reconciler.ffi.mjs
I think this is better overall, since it means it will work consistently in all runtimes and will allow both of them to also work on SVG and MathML elements.
=> :recycle: use a synced attribute instead of conditionally rendering width/height as an attribute or property

src/lustre.gleam
As shared in the issue board:
- https://github.com/lustre-labs/lustre/issues/309
There are few broken links to the guide docs in the hex doc main page.
I guess adding a dot `.` at the front might be sufficient.
=> Trying to fix the broken links to the guide docs in the hex doc main page.

CHANGELOG.md, birdie_snapshots/[html]_default_value_attribute_should_be_rendered_as_value_attribute.accepted, examples/02-inputs/04-forms/src/app.gleam, src/lustre/attribute.gleam, src/lustre/vdom/reconciler.ffi.mjs, src/lustre/vdom/vattr.gleam, test/tests/html_test.gleam
Closes #316. This involves special-casing both the reconciler and the `to_string` implementation for attributes.
The reconciler needs special-casing because we don't want to actually set an attribute at all, we want to set the `defaultValue` property.
The `to_string` implementation needs special-casing because we want to render this attribute as a plain ol' `value` attribute.
=> Add `attribute.default_value` attribute for uncontrolled inputs.

src/lustre/vdom/reconciler.ffi.mjs
close #307 
I'm not sure even this change is worth it. The differences seem minimal except for in Chrome, and from some light testing (running example apps) it looks like it doesn't get hit all that often.
=> :zap: use `previousSibling` when updating adjacent elements in the reconciler

pages/guide/05-server-side-rendering.md
Small PR to update a couple of instances where `bytes_builder` has not been updated to `bytes_tree` in the server-side rendering docs.
=> docs: update references to deprecated bytes_builder module

src/lustre/runtime/client/spa.ffi.mjs, src/lustre/vdom/reconciler.ffi.mjs
If the function is defined inside the class, the property access while exporting it as a function is treated as a possible side effect, forcing the entirety of lustre to be included in the bundle as soon as the `lustre` module is imported.
I also adde _no side effects_ annotations to the attribute hook higher-order functions. this makes it possible for esbuild to remove the `SYNCED_ATTRIBUTE` constant if it's not used.
=> :recycle: move Spa.start function outside of its class

examples/02-inputs/02-decoding-events/src/app.gleam, examples/04-applications/04-hydration/src/app.gleam, examples/05-components/01-basic-setup/src/counter.gleam
Hi, fixes the very few typos I came across in the examples section
=> 📝 Fix typos in examples

README.md
I noticed the link to `inotify-tools` was missing in the README so I added it.
The link is the same as in the hexdocs quickstart manual.
=> doc: Added missing link to `inotify-tools` in README

src/lustre/event.gleam
This is how the doc will look:
=> Make clear on the unit of debounce's `delay` parameter

examples/06-server-components/05-publish-subscribe/README.md, examples/06-server-components/05-publish-subscribe/gleam.toml, examples/06-server-components/05-publish-subscribe/src/app.gleam, examples/06-server-components/05-publish-subscribe/src/whiteboard.gleam, examples/README.md, pages/reference/examples.md, src/lustre/server_component.gleam
uses [glubsub](https://github.com/okkdev/glubsub) to add a simple publish-subscribe mechanism to the whiteboard example.
closes #287, closes #297
=> :memo: add publish-subscribe example

CHANGELOG.md, birdie_snapshots/[html]_advanced_elements_should_be_able_to_be_void_and_non_void.accepted, birdie_snapshots/[html]_keyed_advanced_elements_should_be_able_to_be_void_and_non_void.accepted, birdie_snapshots/[html]_semi_advanced_keyed_tag_functions_should_still_have_the_html_void_checking.accepted, birdie_snapshots/[html]_semi_advanced_tag_functions_should_still_have_the_html_void_checking.accepted, src/lustre/element.gleam, src/lustre/element/keyed.gleam, src/lustre/vdom/vnode.gleam, test/snapshot/html_test.gleam
When I render an advanced element with `element.advanced("", "link", [], [contents], False, False)`, silly as it may seem, it should not be void. It should instead be `<link>contents</link>`.
The checking is maintained for `element.element` and `element.namespaced`. The same changes are done for the keyed functions.
=> Advanced elements should not have the HTML tag voidness checking
