lustre-labs/lustre

README.md

It wasn't compiling with the current version of lustre on hex.

update example in readme

---

src/http.ffi.mjs
src/http_ffi.erl

Disable caching for lustre/try

---

src/lustre/attribute.gleam

wanted role constructor, but was missing
add it!
not an issue if you don't want to accept, and maybe consider doing a11y stuff in a big wave

feat: add role attr

---

src/lustre/element/html.gleam

Ref: https://github.com/lustre-labs/lustre/issues/67

Add children argument to html.option

---

examples/05-http-requests/README.md
examples/06-custom-effects/README.md
gleam.toml
pages/guide/02-state-management.md
pages/guide/03-side-effects.md
pages/hints/pure-functions.md

Also adds a hint page on what we mean by "pure functions."
Closes #90

Create a guide on using and creating side effects.

---

src/client-runtime.ffi.mjs

:bug: Use model from Debug(ForceModel) instead of this.#model

---

src/lustre.gleam

Misc docs fixes

---

pages/guide/04-server-side-rendering.md

:memo: Fix SSR doc missing import

---

pages/reference/for-liveview-devs.md

Does what it says on the tin! I tried to highlight the similarities and difference that stood out to me, but I left out the "fetch data" section for now, since I haven't had a chance to try that yet.
Closes #89

create cheatsheet for LiveView devs

---

src/lustre/attribute.gleam

add missing title attribute, it's a global attribute on all html elements.

Added missing title attribute

---

src/server-component.mjs

This fixes patches with server components in my local installation. By adding the styles, the `stylesOffset` is then calculated correctly.

Fix styles not being added to shadow root styles list

---

src/lustre/element.gleam

"handing" -> "handy"

---

src/lustre/attribute.gleam

add `content` attribute for `meta` elements

add content attribute

---

examples/06-custom-effects/index.html

( just make sure the other examples have the new linke )
```html
"./build/dev/javascript/lustre_ui/priv/styles.css"
```

Fixed the relative link

---

examples/05-http-requests/priv/static/app.mjs
examples/05-http-requests/src/app.gleam

The `05-http-requests` example is currently not working due to the https://api.quotable.io/random api url being out of date. This PR replaces it with https://dummyjson.com/quotes/random

Update random quote api url in 05-http-requests example

---

examples/99-full-stack-applications/client/src/app.gleam

Following full stack app tutorial, there is a fn call on result which is invalid.

remove deprecated function call

---

manifest.toml

🚀 Update manifest to latest versions

---

benchmarks/table-editor/gleam.toml
benchmarks/table-editor/manifest.toml
benchmarks/table-editor/src/app.gleam
benchmarks/table-editor/src/column.gleam
src/lustre.ffi.mjs
src/lustre/runtime/vdom.gleam
src/lustre/server_component.gleam
src/reconciler.ffi.mjs
src/runtime.ffi.mjs
test/lustre/diff_benchmark_test.gleam
test/lustre/diff_test.gleam

I also use components in the table-editor now as a demo :purple_heart:

Adopt parent styles in client components

---

src/lustre/attribute.gleam
src/lustre/element.gleam
src/lustre/element/html.gleam
src/lustre/element/keyed.gleam
src/lustre/runtime/client/reconciler.ffi.mjs
src/lustre/runtime/client/server_component_reconciler.ffi.mjs
src/lustre/runtime/transport.gleam
src/lustre/vdom/attribute.gleam
src/lustre/vdom/diff.gleam
src/lustre/vdom/events.gleam
src/lustre/vdom/node.gleam
test/tests/diff_test.gleam

_yeaaaaaaahhh!!_
Having an official element type means I could simplify lots of the special cases in the to_string functions, too :purple_heart:

Unsafe Inner HTML

---

src/lustre/attribute.gleam
src/lustre/internals/constants.gleam
src/lustre/runtime/client/reconciler.ffi.mjs
src/lustre/vdom/diff.gleam
src/lustre/vdom/events.gleam
src/lustre/vdom/node.gleam
src/lustre/vdom/path.gleam
test/tests/events_test.gleam
test/tests/runtime_test.gleam

Custom path type instead of building the string for every element makes it almost as fast as before!

V5 path performance

---

src/lustre/runtime/client/runtime.ffi.mjs
src/lustre/vdom/virtualise.ffi.mjs

[Simon](https://github.com/lydell) raised an interesting question about how frameworks should handle inputs that have been filled in by the user **before** javascript runs and hydration happens. We implemented a very basic way to handle this where `input` events were fired for non-empty inputs during virtualisation.
This PR addresses some bugs and shortcomings with that approach:
- Fixes a bug in the logic used to determine whether an event should fire in the first place.
- Always fires `"change"` and `"input"` events, in case the user is listening for one or the other.
- Fires a `"blur"` event if the input is not the current active element, in case the user is using blur events for semi-controlled inputs.
- Adjust the runtime such that these events (and any synchronous messages …

Implement smarter input hydration.

---

pages/announcements/2025-04-19.md

Hi!
Just a fix for the HTML forms handling code example in v5 announcement page.
Thanks a lot for all your work on this awesome package.

📝 Fix forms handling code example

---

CHANGELOG.md

:memo: add changelog entries about  style/styles

---

CHANGELOG.md
src/lustre/element/html.gleam

:bug: fix a bug where controlling a textarea would not work

---

examples/03-effects/05-dom-effects/src/app.ffi.mjs
examples/03-effects/05-dom-effects/src/app.gleam
src/lustre/effect.gleam

add a note about the second argument to before_paint/after_paint

---

CHANGELOG.md
examples/02-inputs/03-debouncing/src/app.gleam
src/lustre/event.gleam
src/lustre/vdom/diff.gleam
src/lustre/vdom/reconciler.ffi.mjs
src/lustre/vdom/vattr.gleam

Debounce and throttle

---

CHANGELOG.md
src/lustre/vdom/path.gleam
src/lustre/vdom/reconciler.ffi.mjs
src/lustre/vdom/virtualise.ffi.mjs
test/integration/runtime_test.gleam

:recycle: track paths during node construction instead of event dispatch

---

pages/guide/06-full-stack-applications.md

Ran into a few little things while working through this today, so I thought I'd push up a PR.

🏎️ minor fixup to docs
